



class NotRelativePath(Exception): ...

class ModuleFileTypeNotSupported(Exception): ...

class PathNotFound(Exception): ...

class SysPathNotSet(Exception): ...

class SystemPathNotAdded(Exception): ...

class FunctionNotFoundError(Exception): ...